###
POST http://localhost:5216/Users/register
Content-Type: application/json

{
  "email": "test@test.com",
  "username": "test",
  "password": "password",
  "confirmPassword": "password"
}

###
POST http://localhost:5216/Users/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}
  
###
POST http://localhost:5216/Users/refresh-token
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJuYmYiOjE3MTQ4NTE4NjIsImV4cCI6MTcxNDg1Mjc2MiwiaWF0IjoxNzE0ODUxODYyfQ.BcTnmIP665KvJ07057RkRk0zVkr3i3bt_yqNQDLWNx4",
  "refreshToken": "zprxBvFjwVV5uErUeQ+jqwnC8vP1LPdPMnFyfv2EeQLGd9qjLnmU9WVI6D8VgSvRmRiSGmW/4s9yWBwMbccxdw=="
}

###
POST http://localhost:5216/Users/revoke-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJuYmYiOjE3MTQ4NTI4NjIsImV4cCI6MTcxNDg1Mzc2MiwiaWF0IjoxNzE0ODUyODYyfQ.sffuyKWzRWdoRUtAsZwdIx0kluR-MjSmGYnG6wrejz4

{
  "accessToken": "eyJhbGciOiJfdIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJuYmYiOjE3MTQ4NTI4NjIsImV4cCI6MTcxNDg1Mzc2MiwiaWF0IjoxNzE0ODUyODYyfQ.sffuyKWzRWdoRUtAsZwdIx0kluR-MjSmGYnG6wrejz4",
  "refreshToken": "zprxBvFjwVV5uErUeQ+jqwnC8vP1LPdPMnFyfv2EeQLGd9qjLnmU9WVI6D8VgSvRmRiSGmW/4s9yWBwMbccxdw=="
}